<?php
/**
 * Copyright 2024 DPD Polska Sp. z o.o.
 *
 * NOTICE OF LICENSE
 *
 * Licensed under the EUPL-1.2 or later.
 * You may not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 * It is also bundled with this package in the file LICENSE.txt
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Licence is distributed on an AS IS basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions
 * and limitations under the Licence.
 *
 * @author    DPD Polska Sp. z o.o.
 * @copyright 2024 DPD Polska Sp. z o.o.
 * @license   https://joinup.ec.europa.eu/software/page/eupl
 */

namespace DpdShipping\Api\DpdServices;

if (!defined('_PS_VERSION_')) {
    exit;
}
class DpdServicesClassmap
{
    public static function getCollection(): array
    {
        return [
            'generateProtocolV1' => Type\GenerateProtocolV1::class,
            'dpdServicesParamsV1' => Type\DpdServicesParamsV1::class,
            'pickupAddressDSPV1' => Type\PickupAddressDSPV1::class,
            'sessionDSPV1' => Type\SessionDSPV1::class,
            'packageDSPV1' => Type\PackageDSPV1::class,
            'parcelDSPV1' => Type\ParcelDSPV1::class,
            'authDataV1' => Type\AuthDataV1::class,
            'generateProtocolV1Response' => Type\GenerateProtocolV1Response::class,
            'documentGenerationResponseV1' => Type\DocumentGenerationResponseV1::class,
            'sessionDGRV1' => Type\SessionDGRV1::class,
            'packageDGRV1' => Type\PackageDGRV1::class,
            'parcelDGRV1' => Type\ParcelDGRV1::class,
            'statusInfoDGRV1' => Type\StatusInfoDGRV1::class,
            'generateProtocolV2' => Type\GenerateProtocolV2::class,
            'generateProtocolV2Response' => Type\GenerateProtocolV2Response::class,
            'generateShipmentV1' => Type\GenerateShipmentV1::class,
            'openUMLFeV10' => Type\OpenUMLFeV10::class,
            'packageOpenUMLFeV10' => Type\PackageOpenUMLFeV10::class,
            'parcelOpenUMLFeV4' => Type\ParcelOpenUMLFeV4::class,
            'packageAddressOpenUMLFeV1' => Type\PackageAddressOpenUMLFeV1::class,
            'servicesOpenUMLFeV9' => Type\ServicesOpenUMLFeV9::class,
            'serviceCarryInOpenUMLFeV1' => Type\ServiceCarryInOpenUMLFeV1::class,
            'serviceCODOpenUMLFeV1' => Type\ServiceCODOpenUMLFeV1::class,
            'serviceCODDedicatedAccountOpenUMLFeV1' => Type\ServiceCODDedicatedAccountOpenUMLFeV1::class,
            'serviceCUDOpenUMLeFV1' => Type\ServiceCUDOpenUMLeFV1::class,
            'serviceDeclaredValueOpenUMLFeV1' => Type\ServiceDeclaredValueOpenUMLFeV1::class,
            'serviceDedicatedDeliveryOpenUMLFeV1' => Type\ServiceDedicatedDeliveryOpenUMLFeV1::class,
            'serviceDigitalLabelUMLFeV1' => Type\ServiceDigitalLabelUMLFeV1::class,
            'serviceFlagOpenUMLF' => Type\ServiceFlagOpenUMLF::class,
            'servicePalletOpenUMLFeV1' => Type\ServicePalletOpenUMLFeV1::class,
            'serviceDPDFoodOpenUMLFeV2' => Type\ServiceDPDFoodOpenUMLFeV2::class,
            'serviceDPDLqOpenUMLFeV1' => Type\ServiceDPDLqOpenUMLFeV1::class,
            'serviceDpdPickupOpenUMLFeV1' => Type\ServiceDpdPickupOpenUMLFeV1::class,
            'serviceDutyOpenUMLeFV2' => Type\ServiceDutyOpenUMLeFV2::class,
            'serviceGuaranteeOpenUMLFeV1' => Type\ServiceGuaranteeOpenUMLFeV1::class,
            'serviceInPersOpenUMLFeV1' => Type\ServiceInPersOpenUMLFeV1::class,
            'servicePrivPersOpenUMLFeV1' => Type\ServicePrivPersOpenUMLFeV1::class,
            'serviceRODOpenUMLFeV1' => Type\ServiceRODOpenUMLFeV1::class,
            'serviceSelfColOpenUMLFeV1' => Type\ServiceSelfColOpenUMLFeV1::class,
            'serviceTiresOpenUMLFeV1' => Type\ServiceTiresOpenUMLFeV1::class,
            'serviceTiresExportOpenUMLFeV1' => Type\ServiceTiresExportOpenUMLFeV1::class,
            'generateShipmentV1Response' => Type\GenerateShipmentV1Response::class,
            'shipmentDocumentGenerationResponseV1' => Type\ShipmentDocumentGenerationResponseV1::class,
            'shipmentDocumentGenerationSessionV1' => Type\ShipmentDocumentGenerationSessionV1::class,
            'shipmentDocumentGenerationStatusInfoV1' => Type\ShipmentDocumentGenerationStatusInfoV1::class,
            'generateDomesticReturnLabelV1' => Type\GenerateDomesticReturnLabelV1::class,
            'returnedWaybillsV1' => Type\ReturnedWaybillsV1::class,
            'pudoReturnReceiver' => Type\PudoReturnReceiver::class,
            'generateDomesticReturnLabelV1Response' => Type\GenerateDomesticReturnLabelV1Response::class,
            'generateSpedLabelsV1' => Type\GenerateSpedLabelsV1::class,
            'generateSpedLabelsV1Response' => Type\GenerateSpedLabelsV1Response::class,
            'generateSpedLabelsV4' => Type\GenerateSpedLabelsV4::class,
            'generateSpedLabelsV4Response' => Type\GenerateSpedLabelsV4Response::class,
            'generateSpedLabelsV3' => Type\GenerateSpedLabelsV3::class,
            'generateSpedLabelsV3Response' => Type\GenerateSpedLabelsV3Response::class,
            'generateReturnPackages' => Type\GenerateReturnPackages::class,
            'openUMLFeV7' => Type\OpenUMLFeV7::class,
            'packageOpenUMLFeV7' => Type\PackageOpenUMLFeV7::class,
            'parcelOpenUMLFeV2' => Type\ParcelOpenUMLFeV2::class,
            'servicesOpenUMLFeV6' => Type\ServicesOpenUMLFeV6::class,
            'serviceDPDFoodOpenUMLFeV1' => Type\ServiceDPDFoodOpenUMLFeV1::class,
            'generateReturnPackagesResponse' => Type\GenerateReturnPackagesResponse::class,
            'packagesGenerationResponseV2' => Type\PackagesGenerationResponseV2::class,
            'sessionPGRV2' => Type\SessionPGRV2::class,
            'Packages' => Type\Packages::class,
            'packagePGRV2' => Type\PackagePGRV2::class,
            'ValidationDetails' => Type\ValidationDetails::class,
            'Parcels' => Type\Parcels::class,
            'validationInfoPGRV2' => Type\ValidationInfoPGRV2::class,
            'parcelPGRV2' => Type\ParcelPGRV2::class,
            'generateSpedLabelsV2' => Type\GenerateSpedLabelsV2::class,
            'generateSpedLabelsV2Response' => Type\GenerateSpedLabelsV2Response::class,
            'generatePackagesNumbersV6' => Type\GeneratePackagesNumbersV6::class,
            'openUMLFeV5' => Type\OpenUMLFeV5::class,
            'packageOpenUMLFeV5' => Type\PackageOpenUMLFeV5::class,
            'parcelOpenUMLFeV1' => Type\ParcelOpenUMLFeV1::class,
            'generatePackagesNumbersV6Response' => Type\GeneratePackagesNumbersV6Response::class,
            'generatePackagesNumbersV7' => Type\GeneratePackagesNumbersV7::class,
            'openUMLFeV8' => Type\OpenUMLFeV8::class,
            'packageOpenUMLFeV8' => Type\PackageOpenUMLFeV8::class,
            'parcelOpenUMLFeV3' => Type\ParcelOpenUMLFeV3::class,
            'servicesOpenUMLFeV8' => Type\ServicesOpenUMLFeV8::class,
            'generatePackagesNumbersV7Response' => Type\GeneratePackagesNumbersV7Response::class,
            'generatePackagesNumbersV8' => Type\GeneratePackagesNumbersV8::class,
            'openUMLFeV9' => Type\OpenUMLFeV9::class,
            'packageOpenUMLFeV9' => Type\PackageOpenUMLFeV9::class,
            'generatePackagesNumbersV8Response' => Type\GeneratePackagesNumbersV8Response::class,
            'generatePackagesNumbersV9' => Type\GeneratePackagesNumbersV9::class,
            'openUMLFeV11' => Type\OpenUMLFeV11::class,
            'packageOpenUMLFeV11' => Type\PackageOpenUMLFeV11::class,
            'servicesOpenUMLFeV11' => Type\ServicesOpenUMLFeV11::class,
            'servicePudoToSendUMLFeV1' => Type\ServicePudoToSendUMLFeV1::class,
            //'generatePackagesNumbersV9Response' => Type\GeneratePackagesNumbersV9Response::class,
            'findPostalCodeV1' => Type\FindPostalCodeV1::class,
            'postalCodeV1' => Type\PostalCodeV1::class,
            'findPostalCodeV1Response' => Type\FindPostalCodeV1Response::class,
            'findPostalCodeResponseV1' => Type\FindPostalCodeResponseV1::class,
            'generateInternationalPackageNumbersV1' => Type\GenerateInternationalPackageNumbersV1::class,
            'internationalOpenUMLFeV1' => Type\InternationalOpenUMLFeV1::class,
            'internationalPackageOpenUMLFeV1' => Type\InternationalPackageOpenUMLFeV1::class,
            'internationalParcelOpenUMLFeV1' => Type\InternationalParcelOpenUMLFeV1::class,
            'internationalServicesOpenUMLFeV1' => Type\InternationalServicesOpenUMLFeV1::class,
            'serviceDPDPudoReturnUMLFeV1' => Type\ServiceDPDPudoReturnUMLFeV1::class,
            'generateInternationalPackageNumbersV1Response' => Type\GenerateInternationalPackageNumbersV1Response::class,
            'generatePackagesNumbersV1' => Type\GeneratePackagesNumbersV1::class,
            'openUMLFeV1' => Type\OpenUMLFeV1::class,
            'packageOpenUMLFeV1' => Type\PackageOpenUMLFeV1::class,
            'servicesOpenUMLFeV2' => Type\ServicesOpenUMLFeV2::class,
            'serviceDutyOpenUMLeFV1' => Type\ServiceDutyOpenUMLeFV1::class,
            'generatePackagesNumbersV1Response' => Type\GeneratePackagesNumbersV1Response::class,
            'packagesGenerationResponseV1' => Type\PackagesGenerationResponseV1::class,
            'sessionPGRV1' => Type\SessionPGRV1::class,
            'packagePGRV1' => Type\PackagePGRV1::class,
            'invalidFieldPGRV1' => Type\InvalidFieldPGRV1::class,
            'parcelPGRV1' => Type\ParcelPGRV1::class,
            'generatePackagesNumbersV2' => Type\GeneratePackagesNumbersV2::class,
            'generatePackagesNumbersV2Response' => Type\GeneratePackagesNumbersV2Response::class,
            'generatePackagesNumbersV3' => Type\GeneratePackagesNumbersV3::class,
            'openUMLFeV2' => Type\OpenUMLFeV2::class,
            'packageOpenUMLFeV2' => Type\PackageOpenUMLFeV2::class,
            'servicesOpenUMLFeV3' => Type\ServicesOpenUMLFeV3::class,
            'generatePackagesNumbersV3Response' => Type\GeneratePackagesNumbersV3Response::class,
            'generatePackagesNumbersV4' => Type\GeneratePackagesNumbersV4::class,
            'openUMLFeV3' => Type\OpenUMLFeV3::class,
            'packageOpenUMLFeV3' => Type\PackageOpenUMLFeV3::class,
            'servicesOpenUMLFeV4' => Type\ServicesOpenUMLFeV4::class,
            'generatePackagesNumbersV4Response' => Type\GeneratePackagesNumbersV4Response::class,
            'generatePackagesNumbersV5' => Type\GeneratePackagesNumbersV5::class,
            'openUMLFeV4' => Type\OpenUMLFeV4::class,
            'packageOpenUMLFeV4' => Type\PackageOpenUMLFeV4::class,
            'servicesOpenUMLFeV5' => Type\ServicesOpenUMLFeV5::class,
            'generatePackagesNumbersV5Response' => Type\GeneratePackagesNumbersV5Response::class,
            'packagesPickupCallV3' => Type\PackagesPickupCallV3::class,
            'dpdPickupCallParamsV3' => Type\DpdPickupCallParamsV3::class,
            'pickupCallSimplifiedDetailsDPPV1' => Type\PickupCallSimplifiedDetailsDPPV1::class,
            'pickupPackagesParamsDPPV1' => Type\PickupPackagesParamsDPPV1::class,
            'pickupCustomerDPPV1' => Type\PickupCustomerDPPV1::class,
            'pickupPayerDPPV1' => Type\PickupPayerDPPV1::class,
            'pickupSenderDPPV1' => Type\PickupSenderDPPV1::class,
            'packagesPickupCallV3Response' => Type\PackagesPickupCallV3Response::class,
            'packagesPickupCallResponseV3' => Type\PackagesPickupCallResponseV3::class,
            'statusInfoPCRV2' => Type\StatusInfoPCRV2::class,
            'errorDetailsPCRV2' => Type\ErrorDetailsPCRV2::class,
            'packagesPickupCallV4' => Type\PackagesPickupCallV4::class,
            'packagesPickupCallV4Response' => Type\PackagesPickupCallV4Response::class,
            'packagesPickupCallV1' => Type\PackagesPickupCallV1::class,
            'dpdPickupCallParamsV1' => Type\DpdPickupCallParamsV1::class,
            'contactInfoDPPV1' => Type\ContactInfoDPPV1::class,
            'protocolDPPV1' => Type\ProtocolDPPV1::class,
            'packagesPickupCallV1Response' => Type\PackagesPickupCallV1Response::class,
            'packagesPickupCallResponseV1' => Type\PackagesPickupCallResponseV1::class,
            'protocolPCRV1' => Type\ProtocolPCRV1::class,
            'statusInfoPCRV1' => Type\StatusInfoPCRV1::class,
            'packagesPickupCallV2' => Type\PackagesPickupCallV2::class,
            'dpdPickupCallParamsV2' => Type\DpdPickupCallParamsV2::class,
            'packagesPickupCallV2Response' => Type\PackagesPickupCallV2Response::class,
            'packagesPickupCallResponseV2' => Type\PackagesPickupCallResponseV2::class,
            'appendParcelsToPackageV1' => Type\AppendParcelsToPackageV1::class,
            'parcelsAppendV1' => Type\ParcelsAppendV1::class,
            'parcelsAppendSearchCriteriaPAV1' => Type\ParcelsAppendSearchCriteriaPAV1::class,
            'parcelAppendPAV1' => Type\ParcelAppendPAV1::class,
            'appendParcelsToPackageV1Response' => Type\AppendParcelsToPackageV1Response::class,
            'parcelsAppendResponseV1' => Type\ParcelsAppendResponseV1::class,
            'invalidFieldPAV1' => Type\InvalidFieldPAV1::class,
            'parcelsAppendParcelPAV1' => Type\ParcelsAppendParcelPAV1::class,
            'generateReturnLabelV1' => Type\GenerateReturnLabelV1::class,
            'generateReturnLabelV1Response' => Type\GenerateReturnLabelV1Response::class,
            'getCourierOrderAvailabilityV1' => Type\GetCourierOrderAvailabilityV1::class,
            'senderPlaceV1' => Type\SenderPlaceV1::class,
            'getCourierOrderAvailabilityV1Response' => Type\GetCourierOrderAvailabilityV1Response::class,
            'getCourierOrderAvailabilityResponseV1' => Type\GetCourierOrderAvailabilityResponseV1::class,
            'courierOrderAvailabilityRangeV1' => Type\CourierOrderAvailabilityRangeV1::class,
            'appendParcelsToPackageV2' => Type\AppendParcelsToPackageV2::class,
            'parcelsAppendV2' => Type\ParcelsAppendV2::class,
            'parcelAppendPAV2' => Type\ParcelAppendPAV2::class,
            'appendParcelsToPackageV2Response' => Type\AppendParcelsToPackageV2Response::class,
            'generateProtocolsWithDestinationsV1' => Type\GenerateProtocolsWithDestinationsV1::class,
            'dpdServicesParamsV2' => Type\DpdServicesParamsV2::class,
            'DeliveryDestinations' => Type\DeliveryDestinations::class,
            'sessionDSPV2' => Type\SessionDSPV2::class,
            'packageDSPV2' => Type\PackageDSPV2::class,
            'parcelDSPV2' => Type\ParcelDSPV2::class,
            'pickupAddressDSPV2' => Type\PickupAddressDSPV2::class,
            'deliveryDestination' => Type\DeliveryDestination::class,
            'DepotList' => Type\DepotList::class,
            'protocolDepot' => Type\ProtocolDepot::class,
            'generateProtocolsWithDestinationsV1Response' => Type\GenerateProtocolsWithDestinationsV1Response::class,
            'documentGenerationResponseV2' => Type\DocumentGenerationResponseV2::class,
            'DestinationDataList' => Type\DestinationDataList::class,
            'destinationsData' => Type\DestinationsData::class,
            'nonMatchingData' => Type\NonMatchingData::class,
            'sessionDGRV2' => Type\SessionDGRV2::class,
            'packageDGRV2' => Type\PackageDGRV2::class,
            'parcelDGRV2' => Type\ParcelDGRV2::class,
            'statusInfoDGRV2' => Type\StatusInfoDGRV2::class,
            'generateProtocolsWithDestinationsV2' => Type\GenerateProtocolsWithDestinationsV2::class,
            'generateProtocolsWithDestinationsV2Response' => Type\GenerateProtocolsWithDestinationsV2Response::class,
            'importDeliveryBusinessEventV1' => Type\ImportDeliveryBusinessEventV1::class,
            'dpdParcelBusinessEventV1' => Type\DpdParcelBusinessEventV1::class,
            'dpdParcelBusinessEventDataV1' => Type\DpdParcelBusinessEventDataV1::class,
            'importDeliveryBusinessEventV1Response' => Type\ImportDeliveryBusinessEventV1Response::class,
            'importDeliveryBusinessEventResponseV1' => Type\ImportDeliveryBusinessEventResponseV1::class,
            'DPDServiceException' => Type\DPDServiceException::class,
            'Exception' => Type\Exception::class,
            'DeniedAccessWSException' => Type\DeniedAccessWSException::class,
            'SchemaValidationException' => Type\SchemaValidationException::class,
        ];
    }
}
